### ISSUE TITLE
Option to use nameid as the user lookup attribute

### ISSUE THREAD

**Issue by davehs** [zibasec/django-saml2-pro-auth#33]
I can't see any way to use the name id from the SAMLResponse as the lookup value for users in Django, so if the IDP doesn't supply this as a separate attribute, there is no way to match the user in Django.

Is this something that I've missed, or something that could be added through the settings? If nameid was added to the lookup map then it would make this simple, and would still provide support for custom user models in Django.

**Comment by defionscode** [comment]
@davehs sorry for the delay in responding. To make sure I understand thing correctly, you want the name id to be leverage-able outside of the 'typical' attributes section of the SAMLResponse? Akin to parsing this line 
`      <saml:NameID SPNameQualifier="http://sp.example.com/demo1/metadata.php" Format="urn:oasis:names:tc:SAML:2.0:nameid-format:transient">_ce3d2948b4cf20146dee0a0b3dd6f69b6cf86f62d7</saml:NameID>
`

Correct?

If my understanding of your ask is correct, then you too are correct. We dont currently check that. I don't _think_ it would be _that_ difficult to add. My plate is quite full to deal with enhancements at the moment but I am totally open to a PR otherwise I can likely get to this within a month or two.

**Comment by defionscode** [comment]
@davehs friendly ping, when you're able could you confirm that I understood your ask correctly?

**Comment by davehs** [comment]
@defionscode yes, I think you've got what I'm getting at. I'll put together a PR.

Thanks

**Comment by shepdelacreme** [comment]
Putting this on the docket since we need for our internal use now as well.

**Comment by shepdelacreme** [comment]
Fixed in #38
